spring:
  redis:
    host: 192.168.46.128
    port: 6379
    password: 123456
    database: 0
  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: http://httpbin.org:80/get  # lb://fly-upms
          predicates:
            - Path=/
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1  # 流速 每秒
                redis-rate-limiter.burstCapacity: 3  # 令牌桶的容积
                key-resolver: "#{@remoteAddrKeyResolver}" # SPEL表达式去的对应的bean
            - StripPrefix=1